Made genentries script work with symlinked icon theme paths

diff --git a/extra/genentries b/extra/genentries
--- a/extra/genentries
+++ b/extra/genentries
@@ -25,7 +25,13 @@ if ! [ -z "$icontheme" ]; then
   else
     iconpath="/usr/share/icons/$icontheme"
   fi
-  inherits=$(cat $(find $iconpath -name "index.theme") | sed -n "s|^Inherits=\(.*\)$|\1|p" | sed "s|,|\n|" | grep -v "^hicolor$")
+  indexfile=$(find "$iconpath/" -name "index.theme")
+  if [ -z "$indexfile" ]; then
+    echo "Could not find index.theme in $iconpath for theme $icontheme"
+    exit 1
+  fi
+
+  inherits=$(cat "$indexfile" | sed -n "s|^Inherits=\(.*\)$|\1|p" | sed "s|,|\n|" | grep -v "^hicolor$")
   inherits=$(echo -e "$icontheme\n$inherits\nhicolor" | sed "/^$/d")
 fi
 
@@ -81,10 +87,10 @@ function readdesktopfile {
             paths+=("/usr/share/icons/$theme")
           fi
           for themepath in ${paths[@]}; do
-            if ! [ -d "$themepath" ]; then
+            if [ ! -d "$themepath" ] && [ ! -L "$themepath" ]; then
               continue
             fi
-            sizes=$(find "$themepath" -type d | sed -n "s|^"$themepath"/\([^/]*/\)\{0,1\}\([0-9]*\)[^/]*$|\2|p" | sort -u | awk -v iconsize="$iconsize" '{if($0 > iconsize) print "g "$0}{if($0 == iconsize) print "e "$0}{if ($0 < iconsize) print "l "$0}')
+            sizes=$(find "$themepath/" -type d | sed -n "s|^"$themepath"/\([^/]*/\)\{0,1\}\([0-9]*\)[^/]*$|\2|p" | sort -u | awk -v iconsize="$iconsize" '{if($0 > iconsize) print "g "$0}{if($0 == iconsize) print "e "$0}{if ($0 < iconsize) print "l "$0}')
             sizes=$(echo -e "$(echo "$sizes" | grep "^e.*")\n$(echo "$sizes" | grep "^g.*" | sort -k 2.1n)\nscalable\n$(echo "$sizes" | grep "^l.*" | sort -k 2.1nr)")
             sizes=$(echo "$sizes" | sed "s|^. ||")
             for size in $sizes; do
@@ -95,7 +101,7 @@ function readdesktopfile {
                     break 4
                   fi
                 fi
-              done <<< $(find "$themepath" -type d | grep "^$themepath/\([^/]*/\)\?$size\(x$size\)\?$") 
+              done <<< $(find "$themepath/" -type d | grep "^$themepath/\([^/]*/\)\?$size\(x$size\)\?$") 
             done
           done
         done
